### ISSUE TITLE
Issue with /pay

### ISSUE THREAD

**Issue by LumiFae** [F-Plugins/Economy#4]
The /pay command doesn't work, even with the correct syntax. I can work without it for now but it'd be great if it's fixed

**Comment by negrifelipe** [comment]
Should be fixed. `openmod install Feli.Economy` to update the plugin

**Comment by LumiFae** [comment]
this update causes the plugin "Shops" to not work (openmod plugin)

**Comment by negrifelipe** [comment]
This update does not change things related to the economy provider so its not possible that it broke your shops plugin. Please post your logs @JayXTQ

**Comment by LumiFae** [comment]
i fixed it in the end, restart fixed it. dk why /openmod reload didn't work
