### ISSUE TITLE
Duplication glitch with NPCs

### ISSUE THREAD

**Issue by LumiFae** [F-Plugins/Economy#5]
If you have an NPC that can exchange money for money, like ATMs for example. If you control click on an item it will only cost you the money for 1 item and you will get as much as you have money until it hits the limit. Let's say you have 20k experience and took 10k in the currency out of the ATM whilst control clicking, you will get 2 lots of 10k for the price of 10k.

this doesn't happen in vanilla unturned. maybe something to take a peak into?

**Comment by negrifelipe** [comment]
Not sure if i understood. Can you send a video of the issue ?

**Comment by negrifelipe** [comment]
ups

**Comment by LumiFae** [comment]
One of my friends made a video [here](https://youtu.be/Faf7PjOTqY0) but if you don't understand it then please mention so

**Comment by negrifelipe** [comment]
Looks like xp does not sync correctly with balance will see if implementing some queue or something make it work better

**Comment by LumiFae** [comment]
Yes please, keep me updated. I kinda need this soon as I am the dev of an active server and people are abusing the glitch. Annoying to roll back money yk. Anyway, no stress!

**Comment by LumiFae** [comment]
everything going well? @negrifelipe

**Comment by negrifelipe** [comment]
Will do it when i get the time. You dont have to remind me tl do it that wont make things faster

**Comment by LumiFae** [comment]
> Will do it when i get the time. You dont have to remind me tl do it that wont make things faster

Alright, sorry. Usually people tend to forget to do things and I am used to my friends always forgetting so I like to remind people. Thanks for letting me know that you won’t forget! Take your time. I’ll be awaiting for the fix !

**Comment by negrifelipe** [comment]
Try installing the latest version @JayXTQ Pretty sure it will work now

**Comment by LumiFae** [comment]
Thanks, only just got round to testing this. I have found another issue which I will raise now. Thanks
